server:
  port: 8082
  forward-headers-strategy: framework
  servlet:
    multipart:
      max-file-size: 2GB
      max-request-size: 2GB

spring:
  application:
    name: storage-service
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/iam-2
    username: postgres
    password:
    driver-class-name: org.postgresql.Driver
  jpa:
    auditor-aware-ref: auditorAwareImp
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://localhost:8080/realms/IAMService
          jwk-set-uri: ${spring.security.oauth2.resource-server.jwt.issuer-uri}/protocol/openid-connect/certs
          jwk-set-uris:
            sso: http://localhost:8080/realms/IAMService/protocol/openid-connect/certs
            internal: http://localhost:8081/api/certificate/.well-known/jwks.json
file:
  storage-directory: ./files
  allowed-extensions:
    images: "jpg, jpeg, png, gif, bmp, svg, tiff, webp, heic"
    documents: "docx, pptx, xlsx, pdf, txt"
    codes: "java, html, css, js, cpp, py"
    archives: "zip, rar, 7z, gzip, tar"

  allowed-content-types:
    "image/jpeg, image/png, image/gif, image/bmp, image/svg+xml, image/tiff, image/webp, image/heic,
    application/vnd.openxmlformats-officedocument.wordprocessingml.document,  
    application/vnd.openxmlformats-officedocument.presentationml.presentation,
    application/vnd.openxmlformats-officedocument.spreadsheetml.sheet, application/pdf, text/plain,
    application/octet-stream, application/java-archive, text/html, text/css, application/javascript, 
    text/x-c++, text/x-python, application/zip, application/x-rar-compressed, application/x-7z-compressed, 
    application/gzip, application/x-tar"

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs/storage

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

keycloak:
  enabled: true
  realm: IAMService
  auth-server-url: http://localhost:8080
  client:
    id: storage-service-api
    secret: e8AHJT64AFFiKIdjjwlzZcsqYRD3jk9X